### ISSUE TITLE
Replace vue.js

### ISSUE THREAD

**Issue by simonfrey** [simonfrey/s4#11]
Vue.js is the biggest blog of not understandable code in this project. Would be nice if that could be replaced with a lower attack surface vanilla javascript code

**Comment by karlkeefer** [comment]
Made an attempt at this: https://github.com/simonfrey/s4/pull/17

**Comment by simonfrey** [comment]
Hey Karl, happy new year!

Would be awesome if you could take this over with your proposed DOM based approach.
