### ISSUE TITLE
slight typos in the info tab

### ISSUE THREAD

**Issue by yannlawrency** [simonfrey/s4#2]
two tiny typos in the info tab > about s4 (`frontend/index.html`)

line46: this beautiful little `piece` of math
line47:  in order to not `lose` access

**Comment by Fastidious** [comment]
Also:
> Share your secret with a cryptographical secure method [...]

It should be cryptographically.

**Comment by Fastidious** [comment]
There is more, slightly awkward, grammar. Perhaps the author mother tongue isn't English? Mine isn't. 😄

**Comment by simonfrey** [comment]
Thank you both for the reports! No my mother tongue isn't english. 

Would be super happy if you would be willing to open a PR fixing my weird grammar :+1:
