### ISSUE TITLE
Website does not work offline

### ISSUE THREAD

**Issue by obaqueiro** [simonfrey/s4#20]
Hey! I'm trying to use the S4 website after downloading, but somehow after the page is downloaded (as webpage complete) some Javascript is not being activated.

See:
https://ibb.co/7gXn6Hp

**Comment by obaqueiro** [comment]
I just saw that if I clone the repo and build the latest version it actually works... I'll use that now but you may want to update the webpage with the newest version :)  

Huge thanks for this btw.

**Comment by simonfrey** [comment]
Oh wow. That is a sneaky bug. Thanks for reporting it!

You not by chance have an idea what could be the problem?

**Comment by simonfrey** [comment]
Interesting it seams only to be a problem for decrypting 2 shares. When I increase the decryption to 3 and enter the three shares it also works offline

**Comment by simonfrey** [comment]
aarg. I am testing this over and over again and can't find why it is not working on download, but from loading the file local. Maybe someone else has an idea?

**Comment by karlkeefer** [comment]
I can poke at this at some point this week... Sorry if it's a bug I introduced!

- when running the webpage locally
- the decrypt tab doesn't seem to work (how?)
- with only 2 shares

What is it doing? I watched the screen recording and read this thread and still don't quite understand.

**Comment by simonfrey** [comment]
This is how you can reproduce the bug:
1) Open https://simon-frey.com/s4/
2) Save Page locally (Ctrl+S in Firefox)
3) Open local page
4) Try to decrypt from 2 shares

With decrypting from 3 shares it works :'D

**Comment by simonfrey** [comment]
Fixed by https://github.com/simonfrey/s4/pull/23
