### ISSUE TITLE
How to use the go library ?

### ISSUE THREAD

**Issue by sd65** [simonfrey/s4#24]
Hello,

I'm trying to use the _s4_ go library to encrypt and decrypt bytes.
But when using `import "github.com/simonfrey/s4"` as written in the README, I get a strange error : 

> go: finding github.com/simonfrey/s4 latest
go: downloading github.com/simonfrey/s4 v0.0.0-20210502093622-aa95753ec8f6
go: extracting github.com/simonfrey/s4 v0.0.0-20210502093622-aa95753ec8f6
go: test imports
        github.com/simonfrey/s4: github.com/simonfrey/s4@v0.0.0-20210502093622-aa95753ec8f6: parsing go.mod:
        module declares its path as: s4
                but was required as: github.com/simonfrey/s4

I've tried the rewrite directive in my _go.mod_ but it's only making things worse. How to correctly import this library ?
Thanks !

**Comment by sd65** [comment]
OK, I've managed to get it working with a golang mod replace statement. Sharing the solution here :slightly_smiling_face: 

My go main file : 
```
package main

import (
	"s4"
        "encoding/base64"
)
```

My go.mod file : 
```
module github.com/xxx/yyy/v2

go 1.16

replace s4 => github.com/simonfrey/s4 v0.0.0-20210502093622-aa95753ec8f6

require s4 v0.0.0-00010101000000-000000000000

```

NB : you can replace `v0.0.0-20210502093622-aa95753ec8f6` by `latest` and run `go mod tidy`.

**Comment by simonfrey** [comment]
I tagged the current master with v1.0 to make it work out of the box. 
Could you please try if that fixed it. You should not need the replace anymore.

**Comment by sd65** [comment]
Hi,

I don't think it's related to a tag missing. It's nice though. 

Here's a test _main.go_ : 
```
package main

import (
	"github.com/simonfrey/s4"
)
```

And a related _go.mod_ : 
```
module github.com/xxx/yyy/v2

go 1.16

require github.com/simonfrey/s4 latest
```

I still got the error : 
```
go: github.com/simonfrey/s4@v0.0.0-20210502093622-aa95753ec8f6: parsing go.mod:
	module declares its path as: s4
	        but was required as: github.com/simonfrey/s4

```
I think it's related to the fact that `module` in _s4/go.mod_  is `s4` and not `github.com/simonfrey/s4`.
This may not be all, I'm not completely sure. :slightly_smiling_face:

**Comment by simonfrey** [comment]
Nice catch. Should be fixed with: https://github.com/simonfrey/s4/commit/295f9713af70d434641fa8b3f8615099caffe120

**Comment by sd65** [comment]
Tested on my repo, I think this PR shoudl fix this for good !

I was getting this error without this : 
`../go/pkg/mod/github.com/simonfrey/s4@v0.0.0-20210726193420-57fa43c35b94/s4.go:7:2: package s4/crypto is not in GOROOT (/usr/lib/go-1.17/src/s4/crypto)`

**Comment by sd65** [comment]
Works fine now 🙌
