### ISSUE TITLE
Panic during decryption if the first share field is empty

### ISSUE THREAD

**Issue by kenXengineering** [simonfrey/s4#3]
On the decryption tab, if you leave it set to two or more shares, then fill in a share that is NOT the first text field, it will cause a panic in the Go WASM code.

If the first value is empty, when the code get to [revertShareSlices](https://github.com/simonfrey/s4/blob/master/s4.go#L71), the function takes the length of the first value in the slice, which will be `nil` as the value was empty.  This causes a `panic: runtime error: index out of range [0] with length 0` as the `out` variable is actually 0 in length.

I'm working on a pull request to just dump out of the `recoverShares` function if any of the text fields are empty.

**Comment by simonfrey** [comment]
Thanks for that issue and your pull request! Nice that we have it fixed now :D

It is also already deployed in my hosted version (y)
